package form;

import communication.Communication;
import domain.League;
import domain.PlayedGame;
import domain.Team;
import domain.TeamStatistic;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import table.TeamTableModel;

/**
 *
 * @author Radin
 */
public class FrmShowTable extends javax.swing.JDialog {

    /**
     * Creates new form FrmShowTable
     */
    List<Team> relevantTeams  = new ArrayList<>();
    List<TeamStatistic> relevantStats = new ArrayList<>();
    List<Team> teams;
    List<TeamStatistic> teamStatistics;
    List<League> leagues;
    List<PlayedGame> playedGames;
    League league;
    private TeamTableModel teamTableModel;
    String userRole;
    
    public FrmShowTable(java.awt.Frame parent, boolean modal, String userRole) {
        super(parent, modal);
        this.userRole = userRole;
        initComponents();
        prepareTable();
        
        jbtnUpdate.setVisible("administrator".equals(userRole));
        jcbLeague.addActionListener(e -> onLeagueSelectionChanged());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnUpdate = new javax.swing.JButton();
        jcbLeague = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jcbLeague, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnUpdate)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jcbLeague, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {     
            League league = leagues.get(0);

            teamTableModel.updateStatistics(teams, playedGames, league);
            jTable1.setModel(teamTableModel);

            List<TeamStatistic> teamStatNew = teamTableModel.getTeamStatistics();
            
            boolean pass = false;
            
            for (TeamStatistic newStat : teamStatNew) {
                for (TeamStatistic oldTeamStatistic : teamStatistics) {
                    if(newStat.getTeam().getId().equals(oldTeamStatistic.getTeam().getId()) 
                        && newStat.getLeague().getId().equals(oldTeamStatistic.getLeague().getId())){
                            newStat.setId(oldTeamStatistic.getId());
                            System.out.println(oldTeamStatistic.getId());
                            Communication.getInstance().editTeamStat(newStat);
                            pass = true;
                    }
                }
                if(pass == false){
                    Communication.getInstance().addTeamStat(newStat);                   
                }
                pass = false;
            }
                       
        
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can't update statistics for this tournament.");
            ex.printStackTrace();
        }
    }                                          

   

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<League> jcbLeague;
    // End of variables declaration                   

    private void prepareTable() {
        
        
        
        
        try {
            teams = Communication.getInstance().getAllTeams(new Team());
            teamStatistics = Communication.getInstance().getAllTeamStats(new TeamStatistic());
            leagues = Communication.getInstance().getAllLeagues(new League());
            playedGames = Communication.getInstance().getAllPlayedGames(new PlayedGame());           
                       
            
            for (League league1 : leagues) {
                jcbLeague.addItem(league1);
            }
            
            jcbLeague.setSelectedItem(null);
            
//            league = (League) jcbLeague.getSelectedItem();
//            
//            for (Team team : teams) {
//                for (PlayedGame playedGame : playedGames) {
//                    if(playedGame.getHomeTeam().getId().equals(team.getId()) || playedGame.getAwayTeam().getId().equals(team.getId())){
//                        if(playedGame.getGame().getLeague().getId().equals(league.getId())){
//                            relevantTeams.add(team);
//                            break;
//                        }
//                    }
//                }
//            }
//            
//            
//            for (Team relevantTeam : relevantTeams) {
//                for (TeamStatistic teamStatistic : teamStatistics) {
//                    if(relevantTeam.getId().equals(teamStatistic.getTeam().getId())){
//                        teamStatistic.setTeam(relevantTeam);
//                        relevantStats.add(teamStatistic);
//                        break;
//                    }
//                }
//            }
//            
//           teamTableModel = new TeamTableModel(relevantStats);
//           
//           jTable1.setModel(teamTableModel);

                   
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Cant find rang list for this tournament");
            ex.printStackTrace();
        }
    }

    private void onLeagueSelectionChanged() {
         league = (League) jcbLeague.getSelectedItem();
    
        
        relevantTeams.clear();
        relevantStats.clear();

        
        for (Team team : teams) {
            for (PlayedGame playedGame : playedGames) {
                if (playedGame.getHomeTeam().getId().equals(team.getId()) || 
                    playedGame.getAwayTeam().getId().equals(team.getId())) {

                    if (playedGame.getGame().getLeague().getId().equals(league.getId())) {
                        relevantTeams.add(team);
                        break; 
                    }
                }
            }
        }

        
        for (Team relevantTeam : relevantTeams) {
            for (TeamStatistic teamStatistic : teamStatistics) {
                if (relevantTeam.getId().equals(teamStatistic.getTeam().getId())) {
                    teamStatistic.setTeam(relevantTeam);
                    relevantStats.add(teamStatistic);
                    break; 
                }
            }
        }

        // Update the table model with the filtered statistics
        teamTableModel = new TeamTableModel(relevantStats);
        jTable1.setModel(teamTableModel);
    }
}
