package form;

import communication.Communication;
import domain.Game;
import domain.PlayedGame;
import domain.Player;
import domain.PlayerStatistic;
import domain.Team;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Radin
 */
public class FrmShowPlayerStats extends javax.swing.JDialog {

     
    List<PlayedGame> playedGames;
    List<Team> teams;
    List<Player> players;
    PlayerStatistic playerStats;
    private boolean isEditing = false;
    /**
     * Creates new form FrmShowPlayerStats
     */
    public FrmShowPlayerStats(java.awt.Frame parent, boolean modal, String userRole) throws Exception {
        super(parent, modal);
        initComponents();
        prepareView();
        jbtnEdit.setVisible("administrator".equals(userRole));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtPointsScored = new javax.swing.JTextField();
        jtxtThreePointersAttempted = new javax.swing.JTextField();
        jtxtFreeThrowsMade = new javax.swing.JTextField();
        jtxtThreePointersMade = new javax.swing.JTextField();
        jtxtFreeThrowsAttempted = new javax.swing.JTextField();
        jtxtReboundsOffensive = new javax.swing.JTextField();
        jtxtReboundsDefensive = new javax.swing.JTextField();
        jtxtAssists = new javax.swing.JTextField();
        jtxtMinutesPlayed = new javax.swing.JTextField();
        jtxtSteals = new javax.swing.JTextField();
        jtxtBlocks = new javax.swing.JTextField();
        jtxtPersonalFouls = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbGames = new javax.swing.JComboBox<>();
        jcbTeams = new javax.swing.JComboBox<>();
        jcbPlayers = new javax.swing.JComboBox<>();
        jbtnGame = new javax.swing.JButton();
        jbtnTeam = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnShowPlayerStats = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel9.setText("Assists");

        jLabel10.setText("Steals");

        jLabel11.setText("Blocks");

        jLabel12.setText("Personal fouls");

        jtxtPointsScored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPointsScoredActionPerformed(evt);
            }
        });

        jtxtThreePointersAttempted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtThreePointersAttemptedActionPerformed(evt);
            }
        });

        jtxtFreeThrowsMade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFreeThrowsMadeActionPerformed(evt);
            }
        });

        jtxtThreePointersMade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtThreePointersMadeActionPerformed(evt);
            }
        });

        jtxtFreeThrowsAttempted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFreeThrowsAttemptedActionPerformed(evt);
            }
        });

        jtxtReboundsOffensive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtReboundsOffensiveActionPerformed(evt);
            }
        });

        jtxtReboundsDefensive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtReboundsDefensiveActionPerformed(evt);
            }
        });

        jtxtAssists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAssistsActionPerformed(evt);
            }
        });

        jtxtMinutesPlayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMinutesPlayedActionPerformed(evt);
            }
        });

        jtxtSteals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStealsActionPerformed(evt);
            }
        });

        jtxtBlocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBlocksActionPerformed(evt);
            }
        });

        jtxtPersonalFouls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPersonalFoulsActionPerformed(evt);
            }
        });

        jLabel1.setText("Minutes played");

        jLabel2.setText("Points scored");

        jLabel3.setText("Three pointers made");

        jLabel4.setText("Three pointers attempted");

        jLabel5.setText("Free throws attempted");

        jLabel6.setText("Free throws made");

        jLabel7.setText("Rebounds offensive");

        jLabel8.setText("Rebounds defensive");

        jcbGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGamesActionPerformed(evt);
            }
        });

        jcbTeams.setEnabled(false);

        jcbPlayers.setEnabled(false);

        jbtnGame.setText("Choose");
        jbtnGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGameActionPerformed(evt);
            }
        });

        jbtnTeam.setText("Choose");
        jbtnTeam.setEnabled(false);
        jbtnTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTeamActionPerformed(evt);
            }
        });

        jbtnEdit.setText("Edit");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnShowPlayerStats.setText("Show");
        jbtnShowPlayerStats.setEnabled(false);
        jbtnShowPlayerStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnShowPlayerStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbGames, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGame))
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnTeam))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnShowPlayerStats))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(46, 46, 46)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtPersonalFouls, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtSteals, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtAssists, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtReboundsDefensive, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtReboundsOffensive, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtFreeThrowsAttempted, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtFreeThrowsMade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtThreePointersAttempted, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtPointsScored, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtThreePointersMade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtMinutesPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnEdit)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGame)
                    .addComponent(jbtnTeam)
                    .addComponent(jbtnShowPlayerStats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtMinutesPlayed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtPointsScored, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtThreePointersMade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtThreePointersAttempted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtFreeThrowsMade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtFreeThrowsAttempted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtReboundsOffensive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtReboundsDefensive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtAssists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jtxtSteals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtnEdit)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jtxtBlocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtxtPersonalFouls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>                        

    private void jtxtPointsScoredActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void jtxtThreePointersAttemptedActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void jtxtFreeThrowsMadeActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void jtxtThreePointersMadeActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jtxtFreeThrowsAttemptedActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void jtxtReboundsOffensiveActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jtxtReboundsDefensiveActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void jtxtAssistsActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jtxtMinutesPlayedActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jtxtStealsActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jtxtBlocksActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jtxtPersonalFoulsActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void jcbGamesActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jbtnGameActionPerformed(java.awt.event.ActionEvent evt) {                                         

        jcbTeams.removeAllItems();
        jcbPlayers.removeAllItems();
        jbtnTeam.setEnabled(true);
        jcbTeams.setEnabled(true);
        jcbPlayers.setEnabled(false);
        clearTextFields();

        Game game = (Game) jcbGames.getSelectedItem();
        Set<Long> addedTeamIds = new HashSet<>();

        for (Team team : teams) {
            for (PlayedGame playedGame : playedGames) {
                if(playedGame.getGame().getId().equals(game.getId()) &&
                    (playedGame.getHomeTeam().getId().equals(team.getId()) || playedGame.getAwayTeam().getId().equals(team.getId()))){
                    if (!addedTeamIds.contains(team.getId())) {
                        jcbTeams.addItem(team);
                        addedTeamIds.add(team.getId());
                    }
                    break;
                }
            }
        }
    }                                        

    private void jbtnTeamActionPerformed(java.awt.event.ActionEvent evt) {                                         

        jcbPlayers.removeAllItems();
        jcbPlayers.setEnabled(true);
        jbtnShowPlayerStats.setEnabled(true);
        clearTextFields();

        Team team = (Team) jcbTeams.getSelectedItem();
        Set<Long> addedPlayerIds = new HashSet<>();

        for (Player player : players) {
            if(player.getTeam().getId().equals(team.getId())){
                if (!addedPlayerIds.contains(player.getId())) {
                    jcbPlayers.addItem(player);
                    addedPlayerIds.add(player.getId());
                }
            }
        }
    }                                        

    private void jbtnShowPlayerStatsActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        
        Player player = (Player) jcbPlayers.getSelectedItem();
        Game game = (Game) jcbGames.getSelectedItem();
        PlayerStatistic playerStatistic = new PlayerStatistic();
        playerStatistic.setGame(game);
        playerStatistic.setPlayer(player);
        
        try {           
            playerStats = Communication.getInstance().getPlayerStats(playerStatistic);
            
            if (playerStats != null) {
                jtxtMinutesPlayed.setText(String.valueOf(playerStats.getMinutesPlayed()));
                jtxtPointsScored.setText(String.valueOf(playerStats.getPointsScored()));
                jtxtThreePointersAttempted.setText(String.valueOf(playerStats.getThreePointersAttempted()));
                jtxtThreePointersMade.setText(String.valueOf(playerStats.getThreePointersMade()));
                jtxtFreeThrowsAttempted.setText(String.valueOf(playerStats.getFreeThrowsAttempted()));
                jtxtFreeThrowsMade.setText(String.valueOf(playerStats.getFreeThrowsMade()));
                jtxtReboundsOffensive.setText(String.valueOf(playerStats.getReboundsOffensive()));
                jtxtReboundsDefensive.setText(String.valueOf(playerStats.getReboundsDefensive()));
                jtxtAssists.setText(String.valueOf(playerStats.getAssists()));
                jtxtSteals.setText(String.valueOf(playerStats.getSteals()));
                jtxtBlocks.setText(String.valueOf(playerStats.getBlocks()));
                jtxtPersonalFouls.setText(String.valueOf(playerStats.getPersonalFouls()));
            } else {
                
                JOptionPane.showMessageDialog(this, "No statistics available for the selected player and game.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            //Logger.getLogger(FrmShowPlayerStats.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to retrieve player statistics. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }                                                   

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (!isEditing) {
            
            enableInputFields(true);
            jbtnEdit.setText("Save");
            jbtnGame.setEnabled(false);
            jbtnTeam.setEnabled(false);
            jbtnShowPlayerStats.setEnabled(false);
            jcbTeams.setEnabled(false);
            jcbGames.setEnabled(false);
            jcbPlayers.setEnabled(false);
        } else {           
            try {                
                PlayerStatistic playerStatistic = createPlayerStatisticFromInput();
                Communication.getInstance().editPlayerStats(playerStatistic);
                enableInputFields(false);
                jbtnEdit.setText("Edit"); 
                jbtnGame.setEnabled(true);
                jbtnTeam.setEnabled(true);
                jbtnShowPlayerStats.setEnabled(true);
                jcbTeams.setEnabled(true);
                jcbGames.setEnabled(true);
                jcbPlayers.setEnabled(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Operation Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
        isEditing = !isEditing;
    }                                        

    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnGame;
    private javax.swing.JButton jbtnShowPlayerStats;
    private javax.swing.JButton jbtnTeam;
    private javax.swing.JComboBox<Game> jcbGames;
    private javax.swing.JComboBox<Player> jcbPlayers;
    private javax.swing.JComboBox<Team> jcbTeams;
    private javax.swing.JTextField jtxtAssists;
    private javax.swing.JTextField jtxtBlocks;
    private javax.swing.JTextField jtxtFreeThrowsAttempted;
    private javax.swing.JTextField jtxtFreeThrowsMade;
    private javax.swing.JTextField jtxtMinutesPlayed;
    private javax.swing.JTextField jtxtPersonalFouls;
    private javax.swing.JTextField jtxtPointsScored;
    private javax.swing.JTextField jtxtReboundsDefensive;
    private javax.swing.JTextField jtxtReboundsOffensive;
    private javax.swing.JTextField jtxtSteals;
    private javax.swing.JTextField jtxtThreePointersAttempted;
    private javax.swing.JTextField jtxtThreePointersMade;
    // End of variables declaration                   

    private void prepareView() throws Exception {
        
        playedGames = Communication.getInstance().getAllPlayedGames(new PlayedGame());
        teams = Communication.getInstance().getAllTeams(new Team());
        players = Communication.getInstance().getAllPlayers(new Player());
        
        Set<Long> addedGameIds = new HashSet<>();
        
        List<Game> games = Communication.getInstance().getAllGames(new Game());
        for (Game game : games) {
            for (PlayedGame playedGame : playedGames) {
                if (!addedGameIds.contains(game.getId())) {
                    jcbGames.addItem(game);
                    addedGameIds.add(game.getId());
                }
                break;
            }
        }
        
        enableInputFields(false);
   
    }
    
    private void clearTextFields() {
        jtxtMinutesPlayed.setText("");
        jtxtPointsScored.setText("");
        jtxtThreePointersMade.setText("");
        jtxtThreePointersAttempted.setText("");
        jtxtFreeThrowsMade.setText("");
        jtxtFreeThrowsAttempted.setText("");
        jtxtReboundsOffensive.setText("");
        jtxtReboundsDefensive.setText("");
        jtxtAssists.setText("");
        jtxtSteals.setText("");
        jtxtBlocks.setText("");
        jtxtPersonalFouls.setText("");
    }
    
    private boolean isPositiveNumber(String text) {
        try {
            double value = Double.parseDouble(text);
            return value > 0;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private boolean validateFields(String... fields) {
        // Check if any field is empty
        for (String field : fields) {
            if (field.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields!", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        // Check if all fields are positive numbers
        for (String field : fields) {
            if (!isPositiveNumber(field)) {
                JOptionPane.showMessageDialog(this, "All numerical fields must be positive numbers!", "Validation Error", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }

        return true;
    }
    
    private void enableInputFields(boolean enable) {
        jtxtMinutesPlayed.setEnabled(enable);
        jtxtPointsScored.setEnabled(enable);
        jtxtThreePointersAttempted.setEnabled(enable);
        jtxtFreeThrowsMade.setEnabled(enable);
        jtxtThreePointersMade.setEnabled(enable);
        jtxtFreeThrowsAttempted.setEnabled(enable);
        jtxtReboundsOffensive.setEnabled(enable);
        jtxtReboundsDefensive.setEnabled(enable);
        jtxtAssists.setEnabled(enable);
        jtxtSteals.setEnabled(enable);
        jtxtBlocks.setEnabled(enable);
        jtxtPersonalFouls.setEnabled(enable);
    }
    
    private PlayerStatistic createPlayerStatisticFromInput() throws NumberFormatException {
        int minutesPlayed = Integer.parseInt(jtxtMinutesPlayed.getText());
        int pointsScored = Integer.parseInt(jtxtPointsScored.getText());
        int threePointersAttempted = Integer.parseInt(jtxtThreePointersAttempted.getText());
        int freeThrowsMade = Integer.parseInt(jtxtFreeThrowsMade.getText());
        int threePointersMade = Integer.parseInt(jtxtThreePointersMade.getText());
        int freeThrowsAttempted = Integer.parseInt(jtxtFreeThrowsAttempted.getText());
        int reboundsOffensive = Integer.parseInt(jtxtReboundsOffensive.getText());
        int reboundsDefensive = Integer.parseInt(jtxtReboundsDefensive.getText());
        int assists = Integer.parseInt(jtxtAssists.getText());
        int steals = Integer.parseInt(jtxtSteals.getText());
        int blocks = Integer.parseInt(jtxtBlocks.getText());
        int personalFouls = Integer.parseInt(jtxtPersonalFouls.getText());

        
        return new PlayerStatistic(playerStats.getId(), (Player)jcbPlayers.getSelectedItem(), (Game)jcbGames.getSelectedItem(), minutesPlayed, pointsScored, threePointersMade, threePointersAttempted, freeThrowsMade, freeThrowsAttempted, reboundsOffensive, reboundsDefensive, assists, steals, blocks, personalFouls);
    }
}
